name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:

  update-iers:
    name: Auto-update IERS tables
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'astrofrog/astropy-iers-data' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref_name == 'main' }}
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Download latest IERS files
      run: ./update_data.sh
    - name: Check for changes
      id: check
      run: |
        if git diff --exit-code; then
          echo "changed=true" >> "$GITHUB_OUTPUT"
        else
          echo "changed=false" >> "$GITHUB_OUTPUT"
        fi
    - name: Commit changes
      if: ${{ steps.check.outputs.changed }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add astropy_iers_data/data
        git commit -m "Update IERS Earth rotation and leap second tables"

  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: py39-test
        - macos: py310-test
        - windows: py311-test

  # Automatically tag commits to main with the latest calendar version. Note that
  # this does not currently support two versions in the same day, but if this is
  # needed exceptionally, it is possible to manually push a tag.
  tag:
    name: Tag latest commit to main using calendar version
    needs: tests
    if: ${{ steps.check.outputs.changed }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get tag name from date
        id: tag_name
        run: echo "version=0.$(date +'%Y.%m.%d.%H.%M.%S')" > $GITHUB_OUTPUT
      - name: Check tag
        run: echo ${{ steps.tag_name.outputs.version }}
      - name: Create tag
        if: github.event_name == 'push' && github.ref_name == 'main'
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.tag_name.outputs.version }}

  publish:
    name: Publish the release to PyPI
    needs: tag
    if: ${{ steps.check.outputs.changed }}
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      # The usual tag condition for uploading to PyPI doesn't work because the tag has just been
      # created, but we know we can run on any push to main since this is the same condition for
      # making a tag above.
      upload_to_pypi: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    secrets:
      pypi_token: ${{ secrets.PYPI_TOKEN }}
